name: Pre-prod
on:
  push:
    branches:
      - 58-CI-CD
jobs:
  build:
    name: Send to Expo
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up node
      uses: actions/setup-node@v1
      with:
        node-version: '12.13.1'
    - name: Set up yarn
      run: npm i -g yarn
    - name: Install packages
      run: yarn install --frozen-lockfile
    - name: Set up expo cli
      run: npm i -g expo-cli
    - name: Expo log in
      run: npx expo login -u ${{ secrets.ExpoUsername }} -p ${{ secrets.ExpoPassword }}
    - name: Create env file
      run: echo "${{ secrets.EnvFile }}" > .env
    - name: Send to expo
      run: expo build:android --no-wait